services:
  website:
    build: .
    container_name: citybot-website
    restart: on-failure:10
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`citybot-test-website.duckdns.org`)"
      - "traefik.http.routers.website.entrypoints=web-secure"
      - "traefik.http.routers.website.tls.certresolver=le"
      - "traefik.http.services.website.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
