<script lang="ts" setup>

</script>

<template>
    <div id="gdpr-ge" class="p-20 mt-20">
    <div>
      <h1 class="heading-2">Datenschutzrichtline Deutsch</h1>
      <p class="paragraph-privacy">Zuletzt aktualisiert: April 15, 2023<br>Diese Datenschutzrichtlinie beschreibt unsere Richtlinien und Verfahren zur Erfassung, Verwendung und Offenlegung Ihrer Daten, wenn Sie den Dienst nutzen, und informiert Sie über Ihre Datenschutzrechte und wie das Gesetz Sie schützt. Wir verwenden Ihre persönlichen Daten zur Bereitstellung und Verbesserung des Dienstes. Durch die Nutzung des Dienstes erklären Sie sich mit der Sammlung und Nutzung von Informationen in Übereinstimmung mit dieser Datenschutzerklärungeinverstanden. Diese Datenschutzrichtlinie wurde mit Hilfe des Datenschutzrichtlinien- Generators erstellt.</p>
      <h1 class="h1-privacy">Auslegung und Definitionen</h1>
      <h1 class="h2-privacy">Interpretation</h1>
      <p class="paragraph-privacy">Die Wörter, deren Anfangsbuchstabe groß geschrieben ist, haben die unter den folgenden Bedingungen definierte Bedeutung. Die folgenden Definitionen haben die gleiche Bedeutung, unabhängig davon, ob sie im Singular oder im Plural stehen.</p>
      <h1 class="h2-privacy">Definitionen</h1>
      <p class="paragraph-privacy sub">Für die Zwecke dieser Datenschutzrichtlinie:<br>‍<br><strong>Konto</strong> bezeichnet ein eindeutiges Konto, das für Sie erstellt wurde, um auf unseren Dienst oder Teile unseres Dienstes zuzugreifen. <br><strong>Verbundenes Unternehmen</strong> bedeutet ein Unternehmen, das eine Partei kontrolliert, von ihr kontrolliert wird oder unter gemeinsamer Kontrolle mit ihr steht, wobei "Kontrolle" den Besitz von 50 % oder mehr der Aktien, Anteile oder anderer Wertpapiere bedeutet, die zur Wahl von Direktoren oder anderen Führungsgremien berechtigt sind.<br><strong>Anwendung</strong> bezeichnet das von der Gesellschaft zur Verfügung gestellte Softwareprogramm mit dem Namen CityBot, das von Ihnen auf ein beliebiges elektronisches Gerät heruntergeladen wird.<br><strong>Unternehmen</strong> (in diesem Vertrag entweder als "das Unternehmen", "wir", "uns" oder "unser" bezeichnet) bezieht sich auf CityBot.<br><strong>Land</strong> bezieht sich auf: Schweiz<br><strong>Gerät</strong> bedeutet jedes Gerät, das auf den Dienst zugreifen kann, wie z. B. ein Computer, ein Mobiltelefon oder ein digitales Tablet.<br><strong>Personenbezogene Daten</strong> sind alle Informationen, die sich auf eine identifizierte oder identifizierbare Person beziehen.<br><strong>Service</strong> bezieht sich auf die Anwendung. Dienstanbieter bezeichnet jede natürliche oder juristische Person, die die Daten im Auftrag des Unternehmens verarbeitet. Er bezieht sich auf Drittunternehmen oder Einzelpersonen, die von der Gesellschaft beschäftigt werden, um den Dienst zu erleichtern, den Dienst im Namen der Gesellschaft bereitzustellen, Dienstleistungen im Zusammenhang mit dem Dienst zu erbringen oder die Gesellschaft bei der Analyse der Nutzung des Dienstes zu unterstützen.<br><strong>Drittanbieter-Social-Media-Dienst</strong> bezieht sich auf jede Website oder jede Website eines sozialen Netzwerks, über die sich ein Benutzer anmelden oder ein Konto erstellen kann, um den Dienst zu nutzen.<br><strong>Nutzungsdaten</strong> beziehen sich auf automatisch erfasste Daten, die entweder durch die Nutzung des Dienstes oder durch die Infrastruktur des Dienstes selbst generiert werden (z. B. die Dauer eines Seitenbesuchs).<br><strong>Sie</strong> bedeutet die Einzelperson, die auf den Dienst zugreift oder ihn nutzt, bzw. das Unternehmen oder eine andere juristische Person, in deren Namen eine solche Einzelperson auf den Dienst zugreift oder ihn nutzt, je nach Fall.</p>
      <ul role="list" class="list-2">
        <li><strong>Konto</strong> bezeichnet ein eindeutiges Konto, das für Sie erstellt wurde, um auf unseren Dienst oder Teile unseres Dienstes zuzugreifen. <br></li>
        <li><strong>Verbundenes Unternehmen</strong> bedeutet ein Unternehmen, das eine Partei kontrolliert, von ihr kontrolliert wird oder unter gemeinsamer Kontrolle mit ihr steht, wobei "Kontrolle" den Besitz von 50 % oder mehr der Aktien, Anteile oder anderer Wertpapiere bedeutet, die zur Wahl von Direktoren oder anderen Führungsgremien berechtigt sind.<br></li>
        <li><strong>Anwendung</strong> bezeichnet das von der Gesellschaft zur Verfügung gestellte Softwareprogramm mit dem Namen CityBot, das von Ihnen auf ein beliebiges elektronisches Gerät heruntergeladen wird.<br></li>
        <li><strong>Unternehmen</strong> (in diesem Vertrag entweder als "das Unternehmen", "wir", "uns" oder "unser" bezeichnet) bezieht sich auf CityBot.<br></li>
        <li><strong>Land</strong> bezieht sich auf: Schweiz<br></li>
        <li><br></li>
      </ul>
    </div>
    <div>
      <h1 class="h1-privacy">Erfassen und Verwenden Ihrer persönlichen Daten</h1>
      <h1 class="h2-privacy">Arten von gesammelten Daten</h1>
      <p class="paragraph-privacy"><strong>Persönliche Daten<br></strong>Während der Nutzung unseres Dienstes können wir Sie bitten, uns bestimmte personenbezogene Daten mitzuteilen, die dazu verwendet werden können, Sie zu kontaktieren oder zu identifizieren. Persönlich identifizierbare Informationen können unter anderem sein:<br>‍</p>
      <ul role="list">
        <li>Email Adresse</li>
        <li>Verwendungsdaten</li>
      </ul>
      <p class="paragraph-privacy"><strong>Verwendungsdaten<br></strong>Nutzungsdaten werden bei der Nutzung des Dienstes automatisch erfasst.Nutzungsdaten können Informationen wie die Internetprotokolladresse (z. B. IP-Adresse) Ihres Geräts, den Browsertyp, die Browserversion, die von Ihnen besuchtenSeiten unseres Dienstes, die Uhrzeit und das Datum Ihres Besuchs, die auf diesen Seiten verbrachte Zeit, eindeutige Gerätekennungen und andere Diagnosedaten umfassen. Wenn Sie mit oder über ein mobiles Gerät auf den Dienst zugreifen, können wir bestimmte Informationen automatisch erfassen, einschließlich, aber nicht beschränkt auf den Typ des von Ihnen verwendeten mobilen Geräts, die eindeutige ID Ihres mobilen Geräts, die IP-Adresse Ihres mobilen Geräts, Ihr mobiles Betriebssystem, den Typ des von Ihnen verwendeten mobilen Internetbrowsers, eindeutige Gerätekennungen und andere Diagnosedaten.Wir können auch Informationen sammeln, die Ihr Browser sendet, wenn Sie unseren Dienst besuchen oder wenn Sie auf den Dienst durch oder über ein mobiles Gerät zugreifen.<br>‍</p>
      <p class="paragraph-privacy"><strong>Während der Nutzung der Anwendung gesammelte Informationen<br></strong>Während der Nutzung Unserer Anwendung, um Funktionen Unserer Anwendung bereitzustellen, können Wir, mit Ihrer vorherigen Erlaubnis, sammeln:<br>‍</p>
      <ul role="list">
        <li class="list-item-2">Informationen zu Ihrem Standort</li>
      </ul>
      <p class="paragraph-privacy">Wir verwenden diese Informationen, um Funktionen unseres Dienstes bereitzustellen, um unseren Dienst zu verbessern und anzupassen. Die Informationen können auf die Server des Unternehmens und/oder den Server eines Dienstanbieters hochgeladen oder einfach auf Ihrem Gerät gespeichert werden. Sie können den Zugriff auf diese Informationen jederzeit über die Einstellungen Ihres Geräts aktivieren oder deaktivieren.<br>‍</p>
    </div>
    <div>
      <h1 class="h2-privacy">Verwendung Ihrer persönlichen Daten</h1>
      <p class="paragraph-privacy">Das Unternehmen kann personenbezogene Daten für die folgenden Zwecke verwenden:<br></p>
      <p class="paragraph-privacy sub">Das Unternehmen kann personenbezogene Daten für die folgenden Zwecke verwenden:<br><strong>Zur Bereitstellung und Wartung unseres Dienstes</strong>, einschließlich der Überwachung der Nutzung unseres Dienstes.<br><strong>Um Ihr Konto zu verwalten:</strong> um Ihre Registrierung als Benutzer des Dienstes zu verwalten. Die von Ihnen bereitgestellten persönlichen Daten können Ihnen Zugang zu verschiedenen Funktionalitäten des Dienstes geben, die Ihnen als registriertem Benutzer zur Verfügung stehen.<br><strong>Für die Erfüllung eines Vertrages:</strong> die Entwicklung, Einhaltung und Durchführung des Kaufvertrages für die Produkte, Artikel oder Dienstleistungen, die Sie gekauft haben, oder eines anderen Vertrages mit uns über den Service.<br><strong>Um Sie zu kontaktieren:</strong> Um Sie per E-Mail, Telefonanrufe, SMS oder andere gleichwertige Formen der elektronischen Kommunikation zu kontaktieren, wie z. B. Push-Benachrichtigungen einer mobilen Anwendung in Bezug auf Updates oder informative Mitteilungen im Zusammenhang mit den Funktionalitäten, Produkten oder vertraglichen Dienstleistungen, einschließlich der Sicherheitsupdates, wenn dies für deren Implementierung notwendig oder sinnvoll ist.<br><strong>Um Ihnen</strong> Neuigkeiten, Sonderangebote und allgemeine Informationen über andere Waren, Dienstleistungen und Veranstaltungen, die wir anbieten, <strong>zukommen zu lassen, die denen</strong> ähnlich sind, die Sie bereits gekauft oder angefragt haben, es sei denn, Sie haben sich gegen den Erhalt solcher<br>Informationen entschieden.<br><strong>Um Ihre Anfragen zu verwalten:</strong> Um Ihre Anfragen an uns zu bearbeiten und zu verwalten.<br><strong>Für Geschäftsübertragungen: </strong>Wir können Ihre Daten verwenden, um eine Fusion, Veräußerung, Umstrukturierung, Reorganisation, Auflösung oder einen anderen Verkauf oder eine Übertragung eines Teils oder aller unserer Vermögenswerte zu bewerten oder durchzuführen, sei es als laufender Betrieboder als Teil eines Konkurses, einer Liquidation oder eines ähnlichen Verfahrens, bei dem die von uns gespeicherten personenbezogenen Daten unserer Dienstnutzer zu den übertragenen Vermögenswerten gehören.<br><strong>Für andere Zwecke:</strong> Wir können Ihre Informationen für andere Zwecke verwenden, wie z. B. zur Datenanalyse, zur Ermittlung von Nutzungstrends, zur Bestimmung der Effektivität unserer Werbekampagnen und zur Bewertung und Verbesserung unseres Dienstes, unserer Produkte, Dienstleistungen, unseres Marketings und Ihrer Erfahrungen.</p>
    </div>
    <div>
      <p class="paragraph-privacy">Wir können Ihre persönlichen Daten in den folgenden Situationen weitergeben:<br></p>
      <ul role="list" class="list-3">
        <li><strong>Mit Dienstanbietern:</strong> Wir können Ihre persönlichen Daten mit Dienstanbietern teilen, um die Nutzung unseres Dienstes zu überwachen und zu analysieren, um Sie zu kontaktieren.</li>
        <li><strong>Für Geschäftsübertragungen:</strong> Wir können Ihre personenbezogenen Daten in Verbindung mit oder während der Verhandlungen über eine Fusion, den Verkauf von Unternehmensvermögen, eine Finanzierung oder die Übernahme unseres gesamten oder eines Teils unseres Unternehmens durch ein anderes Unternehmen weitergeben oder übertragen.</li>
        <li><strong>Mit verbundenen Unternehmen:</strong> Wir können Ihre Informationen mit unseren Tochtergesellschaften teilen, in diesem Fall werden wir von diesen Tochtergesellschaften verlangen, diese Datenschutzrichtlinie einzuhalten. Zu den verbundenen Unternehmen gehören unsere Muttergesellschaft und alle anderen Tochtergesellschaften, Joint-Venture-Partner oder andere Unternehmen, die wir kontrollieren oder die unter gemeinsamer Kontrolle mit uns stehen.</li>
        <li><strong>Mit Geschäftspartnern:</strong> Wir können Ihre Informationen mit unseren Geschäftspartnern teilen, um Ihnen bestimmte Produkte, Dienstleistungen oder Werbeaktionen anzubieten.</li>
        <li><strong>Mit anderen Nutzern:</strong> Wenn Sie persönliche Informationen teilen oder anderweitig in den öffentlichen Bereichen mit anderen Nutzern interagieren, können diese Informationen von allen Nutzern eingesehen und öffentlich nach außen verbreitetwerden. Wenn Sie mit anderen Nutzern interagieren oder sich über einen Social- Media-Dienst eines Drittanbieters registrieren, können Ihre Kontakte auf demSocial-Media-Dienst des Drittanbieters Ihren Namen, Ihr Profil, Ihre Bilder und die Beschreibung Ihrer Aktivitäten sehen. In ähnlicher Weise können andere Benutzer Beschreibungen Ihrer Aktivitäten sehen, mit Ihnen kommunizieren und Ihr Profil sehen.</li>
        <li><strong>Mit Ihrem Einverständnis:</strong> Mit Ihrer Zustimmung können wir Ihre persönlichen Daten für jeden anderen Zweck offenlegen.</li>
      </ul>
    </div>
    <div>
      <h1 class="h2-privacy">Aufbewahrung Ihrer persönlichen Daten</h1>
      <p class="paragraph-privacy">Das Unternehmen wird Ihre personenbezogenen Daten nur so lange aufbewahren, wie es für die in dieser Datenschutzrichtlinie genannten Zwecke erforderlich ist. Wir werden Ihre personenbezogenen Daten in dem Umfang aufbewahren und verwenden, der erforderlich ist, um unseren rechtlichen Verpflichtungen nachzukommen (z. B. wenn wir Ihre Daten aufbewahren müssen, um geltende Gesetze einzuhalten), Streitigkeiten beizulegen und unsere rechtlichen Vereinbarungen und Richtlinien durchzusetzen.Das Unternehmen wird Nutzungsdaten auch für interne Analysezwecke aufbewahren. Nutzungsdaten werden im Allgemeinen für einen kürzeren Zeitraum aufbewahrt, es sei denn, diese Daten werden verwendet, um die Sicherheit oder die Funktionalität unseres Dienstes zu verbessern, oder wir sind gesetzlich verpflichtet, diese Daten für längere Zeiträume aufzubewahren.<br></p>
      <h1 class="h2-privacy">Übertragung Ihrer persönlichen Daten</h1>
      <p class="paragraph-privacy">Ihre Informationen, einschließlich personenbezogener Daten, werden in den Betriebsbüros des Unternehmens und an anderen Orten verarbeitet, an denen sich die an der Verarbeitung beteiligten Parteien befinden. Das bedeutet, dass diese Informationen an Computer außerhalb Ihres Staates, Ihrer Provinz, Ihres Landes oder anderer staatlicher Zuständigkeitsbereiche, in denen sich die Datenschutzgesetze von denen Ihres Zuständigkeitsbereichs unterscheiden können, übertragen und dort verwaltet werden können. Ihre Zustimmung zu dieser Datenschutzrichtlinie, gefolgt von Ihrer Übermittlung solcher Informationen, stellt Ihre Zustimmung zu dieser Übertragung dar. Das Unternehmen wird alle angemessenen Schritte unternehmen, um sicherzustellen, dass Ihre Daten sicher und in Übereinstimmung mit dieser Datenschutzrichtlinie behandelt werden, und es wird keine Übertragung Ihrer persönlichen Daten an eine Organisation oder ein Land stattfinden, es sei denn, es sind angemessene Kontrollen vorhanden, die die Sicherheit Ihrer Daten und anderer persönlicher Informationen umfassen.<br></p>
      <h1 class="h2-privacy">Offenlegung Ihrer persönlichen Daten</h1>
      <p class="paragraph-privacy"><strong>Geschäftsvorfälle</strong><br>Wenn das Unternehmen an einer Fusion, einer Übernahme oder einem Verkauf von Vermögenswerten beteiligt ist, können Ihre personenbezogenen Daten übertragen werden. Wir werden Sie darüber informieren, bevor Ihre persönlichen Daten übertragen werden und einer anderen Datenschutzrichtlinie unterliegen. <br>‍<br><strong>Strafverfolgung</strong><br>Unter bestimmten Umständen kann das Unternehmen verpflichtet sein, Ihre persönlichen Daten offenzulegen, wenn dies gesetzlich vorgeschrieben ist oder als Reaktion auf berechtigte Anfragen von Behörden (z. B. einem Gericht oder einer Regierungsbehörde).<br>‍<br><strong>Andere gesetzliche Anforderungen</strong><br>Das Unternehmen kann Ihre persönlichen Daten in dem guten Glauben offenlegen, dass eine solche Handlung notwendig ist, um:<br></p>
      <ul role="list" class="list-4">
        <li>Einer gesetzlichen Verpflichtung nachkommen</li>
        <li>Schutz und Verteidigung der Rechte oder des Eigentums des Unternehmens</li>
        <li>Mögliches Fehlverhalten in Verbindung mit dem Dienst zu verhindern oder zu untersuchen</li>
        <li>die persönliche Sicherheit von Benutzern des Dienstes oder der Öffentlichkeit zu schützen</li>
        <li>Schützen Sie sich vor rechtlicher Haftung</li>
      </ul>
      <h1 class="h2-privacy">Sicherheit Ihrer persönlichen Daten</h1>
      <p class="paragraph-privacy">Die Sicherheit Ihrer persönlichen Daten ist uns wichtig, aber denken Sie daran, dass keine Methode der Übertragung über das Internet oder der elektronischen Speicherung 100% sicher ist. Obwohl wir uns bemühen, kommerziell akzeptable Mittel zum Schutz Ihrer persönlichen Daten zu verwenden, können wir deren absolute Sicherheit nicht garantieren.<br></p>
    </div>
    <div>
      <h1 class="h1-privacy">Links zu anderen Websites</h1>
      <p class="paragraph-privacy">Unser Service kann Links zu anderen Websites enthalten, die nicht von uns betrieben werden. Wenn Sie auf einen Link einer dritten Partei klicken, werden Sie auf die Seite dieser dritten Partei weitergeleitet. Wir empfehlen Ihnen dringend, die Datenschutzrichtlinien jeder Website, die Sie besuchen, zu überprüfen. <br><br>Wir haben keine Kontrolle über und übernehmen keine Verantwortung für den Inhalt, die Datenschutzrichtlinien oder Praktiken von Websites oder Diensten Dritter.<br></p>
    </div>
    <div>
      <h1 class="h1-privacy">Änderungen an dieser Datenschutzrichtlinie</h1>
      <p class="paragraph-privacy">Wir können unsere Datenschutzrichtlinie von Zeit zu Zeit aktualisieren. Wir werden Sie über alle Änderungen informieren, indem wir die neue Datenschutzrichtlinie auf dieser Seite veröffentlichen.<br>‍<br>Wir werden Sie per E-Mail und/oder durch einen auffälligen Hinweis in unserem Service informieren, bevor die Änderung in Kraft tritt, und das Datum der letzten Aktualisierung" oben in dieser Datenschutzrichtlinie aktualisieren.<br>‍<br>Wir empfehlen Ihnen, diese Datenschutzrichtlinie regelmäßig auf Änderungen zu überprüfen. Änderungen an dieser Datenschutzrichtlinie werden wirksam, wenn sie auf dieser Seite veröffentlicht werden.<br></p>
    </div>
    <div>
      <h1 class="h1-privacy">Kontakt</h1>
      <p class="paragraph-privacy">Wenn Sie Fragen zu dieser Datenschutzrichtlinie haben, können Sie uns kontaktieren unter: contact.citybot@gmail.com<br></p>
    </div>
  </div>
     
    <div id="gdpr-en" class="p-20">
    <div>
      <h1 class="heading-2">Privacy Policy English</h1>
      <p class="paragraph-privacy">Last updated: April 15, 2023<br>‍<br>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.<br>‍<br>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p>
      <h1 class="h1-privacy">Interpretation and Definitions</h1>
      <h1 class="h2-privacy">Interpretation</h1>
      <p class="paragraph-privacy">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
      <h1 class="h2-privacy">Definitions</h1>
      <p class="paragraph-privacy sub">For the purposes of this Privacy Policy:<br>‍<br><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.<br><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the<br>shares, equity interest or other securities entitled to vote for election of directors or other managing authority.<br><strong>Application</strong> means the software program provided by the Company downloaded by You on any electronic device, named CityBot<br>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to CityBot.<br><strong>Country</strong> refers to: Switzerland<br><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.<br><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.<br><strong>Service</strong> refers to the Application.<br><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. <br><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.<br><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).<br><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
      <ul role="list" class="list-2">
        <li><strong>Konto</strong> bezeichnet ein eindeutiges Konto, das für Sie erstellt wurde, um auf unseren Dienst oder Teile unseres Dienstes zuzugreifen. <br></li>
        <li><strong>Verbundenes Unternehmen</strong> bedeutet ein Unternehmen, das eine Partei kontrolliert, von ihr kontrolliert wird oder unter gemeinsamer Kontrolle mit ihr steht, wobei "Kontrolle" den Besitz von 50 % oder mehr der Aktien, Anteile oder anderer Wertpapiere bedeutet, die zur Wahl von Direktoren oder anderen Führungsgremien berechtigt sind.<br></li>
        <li><strong>Anwendung</strong> bezeichnet das von der Gesellschaft zur Verfügung gestellte Softwareprogramm mit dem Namen CityBot, das von Ihnen auf ein beliebiges elektronisches Gerät heruntergeladen wird.<br></li>
        <li><strong>Unternehmen</strong> (in diesem Vertrag entweder als "das Unternehmen", "wir", "uns" oder "unser" bezeichnet) bezieht sich auf CityBot.<br></li>
        <li><strong>Land</strong> bezieht sich auf: Schweiz<br></li>
        <li><br></li>
      </ul>
    </div>
    <div>
      <h1 class="h1-privacy">Collecting and Using Your Personal Data</h1>
      <h1 class="h2-privacy">Types of Data Collected</h1>
      <p class="paragraph-privacy"><strong>Personal Data<br></strong>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:<br>‍</p>
      <ul role="list">
        <li>Email address</li>
        <li>Usage Data</li>
      </ul>
      <p class="paragraph-privacy"><strong>Usage Data<br></strong>Usage Data is collected automatically when using the Service.<br>‍<br>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.<br>‍<br>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.<br>‍<br>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.<br>‍</p>
      <p class="paragraph-privacy"><strong>Information Collected while Using the Application<br></strong>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
      <ul role="list">
        <li class="list-item-2">Information regarding your location</li>
      </ul>
      <p class="paragraph-privacy">We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.<br><br>You can enable or disable access to this information at any time, through Your Device settings.</p>
    </div>
    <div>
      <h1 class="h2-privacy">Use of Your Personal Data</h1>
      <p class="paragraph-privacy">The Company may use Personal Data for the following purposes:<br></p>
      <p class="paragraph-privacy sub"><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.<br><strong>To manage Your Account: </strong>to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of<br>the Service that are available to You as a registered user.<br><strong>For the performance of a contract: </strong>the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.<br><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.<br><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.<br><strong>To manage Your requests:</strong> To attend and manage Your requests to Us. <br><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.<br><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
    </div>
    <div>
      <p class="paragraph-privacy">We may share Your personal information in the following situations:<br></p>
      <ul role="list" class="list-3">
        <li><strong>With Service Providers: </strong>We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
        <li><strong>For business transfers: </strong>We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
        <li><strong>With Affiliates: </strong>We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
        <li><strong>With business partners: </strong>We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
        <li><strong>With other users: </strong>when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
        <li><strong>With Your consent: </strong>We may disclose Your personal information for any other purpose with Your consent.</li>
      </ul>
    </div>
    <div>
      <h1 class="h2-privacy">Retention of Your Personal Data</h1>
      <p class="paragraph-privacy">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.<br>‍<br>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.<br></p>
      <h1 class="h2-privacy">Transfer of Your Personal Data</h1>
      <p class="paragraph-privacy">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.<br>‍<br>Your consent to this Privacy Policy followed by Your submission of such information<br>represents Your agreement to that transfer.<br>‍<br>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.<br></p>
      <h1 class="h2-privacy">Disclosure of Your Personal Data</h1>
      <p class="paragraph-privacy"><strong>Business Transactions<br></strong>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.<br>‍<br><strong>Law enforcement</strong><br>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).<br>‍<br><strong>Other legal requirements<br></strong>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:<br></p>
      <ul role="list" class="list-4">
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ul>
      <h1 class="h2-privacy">Security of Your Personal Data</h1>
      <p class="paragraph-privacy">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.<br></p>
    </div>
    <div>
      <h1 class="h1-privacy">Links to Other Websites</h1>
      <p class="paragraph-privacy">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.<br>‍<br>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.<br></p>
    </div>
    <div>
      <h1 class="h1-privacy">Changes to this Privacy Policy</h1>
      <p class="paragraph-privacy">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.<br>‍<br>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.<br>‍<br>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.<br></p>
    </div>
    <div>
      <h1 class="h1-privacy">Contact Us</h1>
      <p class="paragraph-privacy">If you have any questions about this Privacy Policy, You can contact us directly: contact.citybot@gmail.com<br></p>
    </div>
  </div>
</template>
